base_path: ./csvs
train_csv: 'test.csv'
valid_csv: 'test.csv'
test_csv: 'test.csv'

classes: [2,2,2] # Number of classes for each task
num_tasks: 3 # Number of tasks
tasks: ['cancer','candidiasis','cluecell'] #Task names, consistent with the csv files

batch_size: 16
img_batch: 800 # Number of patches per slide
epochs: 3

where: 'UniCAS_res' # Where to save the ckpt and log
lr: 0.00005
logdir: 'train2.log' # Where to save the false predictions for cancer_grade > 1
encoder: 'UniCAS' # Encoders 
embed_dim: 1024 # Embedding dim for the encoder
weights: '' # Wights for the aggregator
depth: 8 # Depth of the aggregator

capacity_factors: [256,256,256,256,256,256,256,256] # Slot for Mult-task aggregator


loss_fns: 'CELoss' 
lr_head: [0.0001,0.0001,0.00001] # If lr_head < 1e-8, the task is not trained
cont: true  # Whether to log the false predictions for cancer_grade > 1 or not
aggregator: 'multi_task' 
loss-weights: 1 # Weight for the sample where cancer_grade > 1 in the loss function
